spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/pindongdong?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&serverTimezone=Asia/Shanghai
  #    password: E94Z3M74kkKA
  #    url: jdbc:mysql://rm-uf6lgnfx2zmto0546.mysql.rds.aliyuncs.com:3306/mall?characterEncoding=utf-8&useSSL=false
#  redis:
#    host: 127.0.0.1
#    port: 6379
#  rabbitmq:
#    addresses: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
server:
  servlet:
    session:
      timeout: 120
